LuminuxHousing/Controllers/Api/PlotController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using AutoMapper;
using LuminuxHousing.Models;

namespace LuminuxHousing.Controllers.Api
{
    public class PlotController : ApiController
    {
        protected ApplicationDbContext _context;

        public PlotController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
           _context.Dispose();
        }

        // GET: api/Plot
        public IQueryable<Plot> GetPlots()
        {
            return _context.Plots.Include(p => p.Size);
        }

        // GET: api/Plot/5
        public IHttpActionResult GetPlot(int id)
        {
            var plot =  _context.Plots.Include(p => p.Size).SingleOrDefault(pId =>pId.Id == id);
            if (plot == null)
                throw new Exception();

            return Ok(plot);
        }

        // PUT: api/Plot/5
        public  IHttpActionResult PutPlot(int id, Plot plot)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != plot.Id)
                throw new Exception();

            _context.Entry(plot).State = EntityState.Modified;

            try
            {
                _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            { 
                return NotFound();
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Plot
        public  IHttpActionResult PostPlot(Plot plot)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            _context.Plots.Add(plot);
            _context.SaveChangesAsync();

            return CreatedAtRoute("DefaultApi", new { id = plot.Id }, plot);
        }

        // DELETE: api/Plot/1
        [HttpDelete]
        public  IHttpActionResult DeletePlot(int id)
        {
            var plot = _context.Plots.SingleOrDefault(p => p.Id == id);
            if (plot == null)
            {
                throw new Exception();
            }
            _context.Plots.Remove(plot);
            _context.SaveChanges();
            return Ok(plot);
        }

       
    }
}

LuminuxHousing/Views/Shared/_FooterPartial.cshtml
    <!--Main Footer-->
    <!--Widgets Section-->
    <div class="widgets-section">
        <div class="auto-container">
            <div class="row clearfix">
                <!--Big Column-->
                <div class="big-column col-md-6 col-sm-12 col-xs-12">
                    <div class="row clearfix">
                        <!--Footer Column-->
                        <div class="footer-column col-md-7 col-sm-6 col-xs-12">
                            <div class="footer-widget about-widget">
                                <h2>Luminux Housing</h2>
                                <div class="widget-content">
                                    <div class="text">Sed perspiciatis unde omnis iste natus elit voluptatem accusantium doloremque site laudantium totam rem aperiam.</div>
                                    <div class="copyright-text">&copy; Luminux Housing @DateTime.Now.Year, All Rights Reserved.</div>

                                </div>
                            </div>
                        </div><!--End Footer Column-->
                        <!--Footer Column-->
                        <div class="footer-column col-md-5 col-sm-6 col-xs-12">
                            <div class="footer-widget links-widget">
                                <h2>Quick Links</h2>
                                <div class="widget-content">
                                    <ul class="list">
                                        <li><a href="@Url.Action("About","Home")">About</a></li>
                                        <li><a href="@Url.Action("Contact","Home")">Contact</a></li>
                                        <li><a href="#">Support Center</a></li>
                                        <li><a href="#">Terms & Conditions</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div><!--End Footer Column-->
                    </div>
                </div><!--End Big Column-->
                <!--Big Column-->
                <div class="big-column col-md-6 col-sm-12 col-xs-12">
                    <div class="row clearfix">


                        <!--Footer Column-->
                        <div class="footer-column col-md-7 col-sm-6 col-xs-12">
                            <div class="footer-widget contact-widget">
                                <h2>Contact Us</h2>
                                <div class="widget-content">
                                    <div class="text">Feel free to ger in touch with us via phone or send us a message.</div>
                                    <ul class="contact-info">
                                        <li>
                                            <div class="icon"><span class="fa fa-envelope-o"></span></div> <a href="mailto:contact@luminuxhousing.com">contact@luminuxhousing.com</a>
                                        </li>
                                        <li>
                                            <div class="icon"><span class="fa fa-phone"></span></div> +880 100 000 0000
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div><!--End Footer Column-->
                        <!--Footer Column-->
                        <div class="footer-column col-md-5 col-sm-6 col-xs-12">
                            <div class="footer-widget social-widget">
                                <h2>Folow Us</h2>
                                <div class="widget-content">
                                    <ul class="social-links">
                                        <li><a href="https://www.facebook.com/luminuxhousing" class="facebook"><span class="fa fa-facebook-f"></span></a></li>
                                        <li><a href="https://twitter.com/luminuxhousing" class="twitter"><span class="fa fa-twitter"></span></a></li>
                                        <li><a href="https://plus.google.com/up/luminuxhousing" class="google-plus"><span class="fa fa-google-plus"></span></a></li>
                                        <li><a href="https://www.linkedin.com/luminuxhousing" class="linkedin"><span class="fa fa-linkedin"></span></a></li>
                                        <li><a href="https://www.instagram.com/luminuxhousing" class="instagram"><span class="fa fa-instagram"></span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div><!--End Footer Column-->

                    </div>
                </div><!--End Big Column-->

            </div>
        </div>
    </div>

<!--End Main Footer-->

LuminuxHousing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Luminux Housing</title>
    <link href="~/Content/TemplateFile/css/bootstrap.css" rel="stylesheet">
    <link href="~/Content/TemplateFile/css/style.css" rel="stylesheet">
    <link rel="shortcut icon" href="~/Content/TemplateFile/images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/Content/TemplateFile/images/favicon.ico" type="image/x-icon">
    <!-- Responsive -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link href="~/Content/TemplateFile/css/responsive.css" rel="stylesheet">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Luminux Housing", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Project", "ProjectDetails", "Plot")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content jumbotron">
        @RenderBody()

        <hr />

        <footer class="main-footer with-padding-top">
            @Html.Partial("_FooterPartial")
        </footer>
    </div>

    <script src="~/Content/TemplateFile/js/jquery.js"></script>
    <script src="~/Content/TemplateFile/js/bootstrap.min.js"></script>
    <script src="~/Content/TemplateFile/js/jquery-ui.js"></script>
    <script src="~/Content/TemplateFile/js/jquery.fancybox.pack.js"></script>
    <script src="~/Content/TemplateFile/js/jquery.fancybox-media.js"></script>
    <script src="~/Content/TemplateFile/js/mixitup.js"></script>
    <script src="~/Content/TemplateFile/js/owl.js"></script>
    <script src="~/Content/TemplateFile/js/wow.js"></script>
    <script src="~/Content/TemplateFile/js/appear.js"></script>
    <script src="~/Content/TemplateFile/js/script.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)
</body>
</html>